= Cahier De Recette - SAE Chasse au Trésor
:toc:
:toc-position: preamble
:toc-title: Sommaire
:title-page:
:sectnums:
:stem: asciimath
:Entreprise: Chasse au Trésor
:Equipe:
:badge: https://img.shields.io/badge/
:test_ok: image:{badge}Test-Passé-blue.svg[]
:test_ko: image:{badge}Test-Echoué-red.svg[]
:test_wt: image:{badge}Test-En%20Attente-orange.svg[]


* Thomas Duppi
* Loélia Demany
* Loïs Pacqueteau
* Vincent Barette

Sprint 2, Janvier 2024, Groupe G3A-5

== Introduction
=== Objet :
[.text-justify]
Ce document a été produit dans le cadre d'un projet d'élaboration d'une vue pour le jeu de Chasse au trésor de Quentin Vey et Adrien van den Bossche.


== Pre-Requis :
[.text-justify]
L'exécution des tests spécifiés au chapitre suivant requiert :

* Un sniffeur de la chasse au trésor.
* L'environnement de test tel que spécifié dans la partie "Environnement de test" de ce document.
* Les fiches de tests. *À vérifier*


=== Éléments à tester :
[.text-justify]
Les éléments testés concernent les Use-Cases spécifiées dans la https://github.com/IUT-Blagnac/sae-3-01-devapp-g3a-5/blob/master/Documentation/Documentation%20technique.adoc[documentation technique] et le https://github.com/IUT-Blagnac/sae-3-01-devapp-g3a-5[README.md] du projet.


=== Environnement de test :
[.text-justify]
Ordinateur sous Windows ou OS équivalent.



== Cas de test :
=== Fonctionnalités Panel Spectateur :
:lvl1: 1
> Ces présents tests concernent l'IHM Spectateur - celle avec le parcours et les pions.

==== https://github.com/IUT-Blagnac/sae-3-01-devapp-g3a-5/issues/29[Equipe Connexion]
:lvl2: 1


// ///////// DEBUT DE NOUVEAU TEST ///////////
// Définissez les informations de votre test!
:num_test: 1
:nom_test: Connexion Avant Partie
:objectif: Vérifier qu'il est possible de rejoindre la partie avant son lancement

// Ne pas toucher ⬇️
:test_id: image:{badge}Test%20{lvl1}.{lvl2}-{num_test}-orange.svg[link=""]
// Ne pas toucher ⬆️

[width="300%"]
|====
>| Cas de test 4+| {test_id}
>| Titre 4+| {nom_test}
>| Objectif 4+| {objectif}
5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat

^|{lvl1}.{lvl2}.*{num_test}.1* ^|Connecter un sniffeur. ^|Le joueur apparaît après https://github.com/IUT-Blagnac/sae-3-01-devapp-g3a-5/issues/33[raffraichissement]. ^| Être sur la page index, disposer d'un sniffeur. ^|{test_wt}
^|{lvl1}.{lvl2}.*{num_test}.2* ^|Connecter plusieurs sniffeurs. ^|Les joueurs apparaissent après https://github.com/IUT-Blagnac/sae-3-01-devapp-g3a-5/issues/33[raffraichissement]. ^| Être sur la page index, disposer d'un sniffeur. ^|{test_wt}
^|{lvl1}.{lvl2}.*{num_test}.3* ^|Connecter un sniffeur ^|Le sniffeur se lance sans problème, et apparait sur la page lors du rafraichissement (automatique que la page se lance...). ^| Ne PAS être sur la page index, disposer d'un sniffeur. ^|{test_wt}
5+|
|====


// ///////// DEBUT DE NOUVEAU TEST ///////////
// Définissez les informations de votre test!
:num_test: 2
:nom_test: Connexion Pendant Partie
:objectif: Vérifier qu'il est possible de rejoindre une partie en cours

// Ne pas toucher ⬇️
:test_id: image:{badge}Test%20{lvl1}.{lvl2}-{num_test}-orange.svg[link=""]
// Ne pas toucher ⬆️

[width="300%"]
|====
>| Cas de test 4+| {test_id}
>| Titre 4+| {nom_test}
>| Objectif 4+| {objectif}
5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat

^|{lvl1}.{lvl2}.*{num_test}.1* ^|Connecter un sniffeur. ^|Le joueur apparaît dès lors qu'il trouve le premier trésor. ^| Être sur la page admin ou user, disposer d'un sniffeur. ^|{test_wt}
^|{lvl1}.{lvl2}.*{num_test}.2* ^|Connecter plusieurs sniffeurs. ^|Les joueurs apparaissent dès lors qu'ils trouvent le premier trésor. ^| Être sur la page index, disposer d'un sniffeur. ^|{test_wt}
5+|

5+|Commentaire : Aucun commentaire.
|====


// ///////////////////////////////////////////


// ///////// DEBUT DE NOUVEAU TEST ///////////
// Définissez les informations de votre test!
:num_test: 3
:nom_test: Reset Joueur
:objectif: S'assurer que le joueur se remette bien à 0 lorsque l'on veut rejouer

// Ne pas toucher ⬇️
:test_id: image:{badge}Test%20{lvl1}.{lvl2}-{num_test}-pink.svg[link=""]
// Ne pas toucher ⬆️

[width="300%"]
|====
>| Cas de test 4+| {test_id}
>| Titre 4+| {nom_test}
>| Objectif 4+| {objectif}
5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat

^|{lvl1}.{lvl2}.*{num_test}.1* ^|Déconnecter et reconnecter un sniffeur, puis trouver le 1er trésor. ^| Les scores et les temps sont remis à 0. ^| Ce sniffeur était connecté, mais n'avait pas encore trouvé le 1er trésor. ^|{test_wt}
^|{lvl1}.{lvl2}.*{num_test}.2* ^|Déconnecter et reconnecter un sniffeur, puis trouver le 1er trésor. ^| Les scores et les temps sont remis à 0. ^| Ce sniffeur était en train de jouer. ^|{test_wt}
^|{lvl1}.{lvl2}.*{num_test}.3* ^|Déconnecter et reconnecter un sniffeur, puis trouver le 1er trésor. ^| Les scores et les temps sont remis à 0. ^| Ce sniffeur avait terminé sa partie. ^|{test_wt}
5+|

5+|Commentaire : Aucun commentaire.
|====
// ///////////////////////////////////////////


=== Fonctionnalités Panel Administrateur :
:lvl1: 1
> Ces tests ne regardent que le panel des administrateurs.

==== Gestion des joueurs :
:lvl2: 2


// ///////// DEBUT DE NOUVEAU TEST ///////////
// Définissez les informations de votre test!
:num_test: 1
:nom_test: Création d'un nouveau client
:objectif: Vérifier qu'il est possible de créer un nouveau client

// Ne pas toucher ⬇️
:test_id: image:{badge}Test%20{lvl1}.{lvl2}-{num_test}-orange.svg[link=""]
// Ne pas toucher ⬆️

[width="300%"]
|====
>| Cas de test 4+| {test_id}
>| Titre 4+| {nom_test}
>| Objectif 4+| {objectif}
5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|{lvl1}.{lvl2}.*{num_test}.1* ^|Cliquer sur le bouton "Nouveau client". ^|La fenêtre de création des clients s'ouvre. ^| Aucune ^|{test_ko}
5+|

5+|Commentaire : blabla
|====
// ///////////////////////////////////////////
