= Cahier De Recette - SAE Chasse au Trésor
:toc:
:toc-position: preamble
:toc-title: Sommaire
:title-page:
// :sectnums: NE PAS REACTIVER SVP
:stem: asciimath
:Entreprise: Chasse au Trésor
:Equipe:
:badge: https://img.shields.io/badge/
:test_ok: image:{badge}Test-Passé-blue.svg[]
:test_ko: image:{badge}Test-Echoué-red.svg[]
:test_wt: image:{badge}Test-En%20Attente-orange.svg[]


* Thomas Duppi
* Loélia Demany
* Loïs Pacqueteau
* Vincent Barette

Sprint 2, Janvier 2024, Groupe G3A-5

== Introduction
=== Objet
[.text-justify]
Ce document a été produit dans le cadre d'un projet d'élaboration d'une vue pour le jeu de Chasse au trésor de Quentin Vey et Adrien van den Bossche.


== Pre-Requis
[.text-justify]
L'exécution des tests spécifiés au chapitre suivant requiert :

* Un sniffeur de la chasse au trésor.
* L'environnement de test tel que spécifié dans la partie "Environnement de test" de ce document.
* Les fiches de tests. *À vérifier*


=== Éléments à tester
[.text-justify]
Les éléments testés concernent les Use-Cases spécifiées dans la https://github.com/IUT-Blagnac/sae-3-01-devapp-g3a-5/blob/master/Documentation/Documentation%20technique.adoc[documentation technique] et le https://github.com/IUT-Blagnac/sae-3-01-devapp-g3a-5[README.md] du projet.


=== Environnement de test
[.text-justify]
Ordinateur sous Windows ou OS équivalent.



== Cas de test
=== Fonctionnalités Panel Spectateur
:lvl1: 1
> Ces présents tests concernent l'IHM Spectateur - celle avec le parcours et les pions.

==== https://github.com/IUT-Blagnac/sae-3-01-devapp-g3a-5/issues/29[Equipe Connexion]
:lvl2: 1


// ///////// DEBUT DE NOUVEAU TEST ///////////
// Définissez les informations de votre test!
:num_test: 1
:nom_test: Connexion Avant Partie
:objectif: Vérifier qu'il est possible de rejoindre la partie avant son lancement

// Ne pas toucher ⬇️
:test_id: image:{badge}Test%20{lvl1}.{lvl2}-{num_test}-pink.svg[link=""]
// Ne pas toucher ⬆️

[width="300%"]
|====
>| Cas de test 4+| {test_id}
>| Titre 4+| {nom_test}
>| Objectif 4+| {objectif}
5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat

^|{lvl1}.{lvl2}.*{num_test}.1* ^|Connecter un sniffeur. ^|Le joueur apparaît après https://github.com/IUT-Blagnac/sae-3-01-devapp-g3a-5/issues/33[raffraichissement]. ^| Être sur la page index, disposer d'un sniffeur. ^|{test_wt}
^|{lvl1}.{lvl2}.*{num_test}.2* ^|Connecter plusieurs sniffeurs. ^|Les joueurs apparaissent après https://github.com/IUT-Blagnac/sae-3-01-devapp-g3a-5/issues/33[raffraichissement]. ^| Être sur la page index, disposer d'un sniffeur. ^|{test_wt}
^|{lvl1}.{lvl2}.*{num_test}.3* ^|Connecter un sniffeur ^|Le sniffeur se lance sans problème, et apparait sur la page lors du rafraichissement (automatique que la page se lance...). ^| Ne PAS être sur la page index, disposer d'un sniffeur. ^|{test_wt}
5+|
|====


// ///////// DEBUT DE NOUVEAU TEST ///////////
// Définissez les informations de votre test!
:num_test: 2
:nom_test: Connexion Pendant Partie
:objectif: Vérifier qu'il est possible de rejoindre une partie en cours

// Ne pas toucher ⬇️
:test_id: image:{badge}Test%20{lvl1}.{lvl2}-{num_test}-pink.svg[link=""]
// Ne pas toucher ⬆️

[width="300%"]
|====
>| Cas de test 4+| {test_id}
>| Titre 4+| {nom_test}
>| Objectif 4+| {objectif}
5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat

^|{lvl1}.{lvl2}.*{num_test}.1* ^|Connecter un sniffeur. ^|Le joueur apparaît dès lors qu'il trouve le premier trésor. ^| Être sur la page admin ou user, disposer d'un sniffeur. ^|{test_wt}
^|{lvl1}.{lvl2}.*{num_test}.2* ^|Connecter plusieurs sniffeurs. ^|Les joueurs apparaissent dès lors qu'ils trouvent le premier trésor. ^| Être sur la page admin ou user, disposer d'un sniffeur. ^|{test_wt}
5+|

5+|Commentaire : Aucun commentaire.
|====


// ///////////////////////////////////////////


// ///////// DEBUT DE NOUVEAU TEST ///////////
// Définissez les informations de votre test!
:num_test: 3
:nom_test: Reset Joueur
:objectif: S'assurer que le joueur se remette bien à 0 lorsque l'on veut rejouer

// Ne pas toucher ⬇️
:test_id: image:{badge}Test%20{lvl1}.{lvl2}-{num_test}-pink.svg[link=""]
// Ne pas toucher ⬆️

[width="300%"]
|====
>| Cas de test 4+| {test_id}
>| Titre 4+| {nom_test}
>| Objectif 4+| {objectif}
5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat

^|{lvl1}.{lvl2}.*{num_test}.1* ^|Déconnecter et reconnecter un sniffeur, puis trouver le 1er trésor. ^| Les scores et les temps sont remis à 0. ^| Ce sniffeur était connecté, mais n'avait pas encore trouvé le 1er trésor. ^|{test_wt}
^|{lvl1}.{lvl2}.*{num_test}.2* ^|Déconnecter et reconnecter un sniffeur, puis trouver le 1er trésor. ^| Les scores et les temps sont remis à 0. ^| Ce sniffeur était en train de jouer. ^|{test_wt}
^|{lvl1}.{lvl2}.*{num_test}.3* ^|Déconnecter et reconnecter un sniffeur, puis trouver le 1er trésor. ^| Les scores et les temps sont remis à 0. ^| Ce sniffeur avait terminé sa partie. ^|{test_wt}
5+|

5+|Commentaire : Aucun commentaire.
|====
// ///////////////////////////////////////////




==== https://github.com/IUT-Blagnac/sae-3-01-devapp-g3a-5/issues/54[Couleur Plateau]
:lvl2: 2


// ///////// DEBUT DE NOUVEAU TEST ///////////
// Définissez les informations de votre test!
:num_test: 1
:nom_test: Vérification Couleur Plateau
:objectif: S'assurer que les couleurs sont conformes à la charte graphique

// Ne pas toucher ⬇️
:test_id: image:{badge}Test%20{lvl1}.{lvl2}-{num_test}-pink.svg[link=""]
// Ne pas toucher ⬆️

[width="300%"]
|====
>| Cas de test 4+| {test_id}
>| Titre 4+| {nom_test}
>| Objectif 4+| {objectif}
5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat

^|{lvl1}.{lvl2}.*{num_test}.1* ^|Ouvrir la page utilisateur/spectateur. ^|Le plateau tend vers le foncé et revient vers du clair sur la dernière case. ^| 6 checkpoints sont connectés ou simulés (pour 6 cases). ^|{test_ok}
^|{lvl1}.{lvl2}.*{num_test}.2* ^|Ouvrir la page utilisateur/spectateur. ^|Le plateau tend vers le foncé et revient vers du clair et repart sur du foncé. ^| 11 checkpoints sont connectés ou simulés (pour 11 cases). ^|{test_ok}
5+|
|====


// ///////// DEBUT DE NOUVEAU TEST ///////////
// Définissez les informations de votre test!
:num_test: 2
:nom_test: Intégrité Couleur Plateau
:objectif: S'assurer que les couleurs du plateau ne changent jamais (qu'il n'y a pas d'aléatoire dans la fonction)

// Ne pas toucher ⬇️
:test_id: image:{badge}Test%20{lvl1}.{lvl2}-{num_test}-pink.svg[link=""]
// Ne pas toucher ⬆️

[width="300%"]
|====
>| Cas de test 4+| {test_id}
>| Titre 4+| {nom_test}
>| Objectif 4+| {objectif}
5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat

^|{lvl1}.{lvl2}.*{num_test}.1* ^|Ouvrir plusieurs pages utilisateur/spectateur. ^|Le plateau ressemble toujours à la même chose. ^| Au moins 1 checkpoint est connecté ou simulé. ^|{test_ok}
5+|

5+|Commentaire : Aucun commentaire.
|====


// ///////////////////////////////////////////





==== https://github.com/IUT-Blagnac/sae-3-01-devapp-g3a-5/issues/58[Plateau Adaptation Taille]
:lvl2: 3


// ///////// DEBUT DE NOUVEAU TEST ///////////
// Définissez les informations de votre test!
:num_test: 1
:nom_test: Plateau Adaptation Taille
:objectif: Vérifier que la taille du plateau s'adapte au nombre de checkpoints connectés ou simulés

// Ne pas toucher ⬇️
:test_id: image:{badge}Test%20{lvl1}.{lvl2}-{num_test}-pink.svg[link=""]
// Ne pas toucher ⬆️

[width="300%"]
|====
>| Cas de test 4+| {test_id}
>| Titre 4+| {nom_test}
>| Objectif 4+| {objectif}
5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat

^|{lvl1}.{lvl2}.*{num_test}.1* ^|Ouvrir la page utilisateur/spectateur. ^|Le plateau dispose de 6 cases. ^| 6 checkpoints sont connectés ou simulés (pour 6 cases). ^|{test_ok}
^|{lvl1}.{lvl2}.*{num_test}.2* ^|Ouvrir la page utilisateur/spectateur. ^|Le plateau dispose de 11 cases. ^| 11 checkpoints sont connectés ou simulés (pour 11 cases). ^|{test_ok}
5+|
|====




=== Fonctionnalités Diverses
:lvl1: *
> Ces présents tests sont divers car ils rentrent dans plusieurs ou aucune des catégories ci-dessus.

==== https://github.com/IUT-Blagnac/sae-3-01-devapp-g3a-5/issues/67[Accès Port Série]
:lvl2: 1


// ///////// DEBUT DE NOUVEAU TEST ///////////
// Définissez les informations de votre test!
:num_test: 1
:nom_test: Accès Port Série
:objectif: Accéder au port série et lire des données

// Ne pas toucher ⬇️
:test_id: image:{badge}Test%20{lvl1}.{lvl2}-{num_test}-pink.svg[link=""]
// Ne pas toucher ⬆️

[width="300%"]
|====
>| Cas de test 4+| {test_id}
>| Titre 4+| {nom_test}
>| Objectif 4+| {objectif}
5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat

^|{lvl1}.{lvl2}.*{num_test}.1* ^|Démarrer l'outil de sélection de port série avec le bouton puis choisir le port série (généralement COM3). ^|Des données apparaissent dans la console JS. ^|Être sur la page index, utiliser Google Chrome. ^|{test_wt}
^|{lvl1}.{lvl2}.*{num_test}.1* ^|Démarrer l'outil de sélection de port série et annuler l'opération. ^|Cela ne déclenche Aucune erreur n'apparait dans la console JS. ^|Être sur la page index, utiliser Google Chrome. ^|{test_wt}
5+|
|====


==== https://github.com/IUT-Blagnac/sae-3-01-devapp-g3a-5/issues/62[Données Admin]
:lvl2: 2


// ///////// DEBUT DE NOUVEAU TEST ///////////
// Définissez les informations de votre test!
:num_test: 2
:nom_test: Données Conformes
:objectif: Vérifier que les données du port série sont conformes

// Ne pas toucher ⬇️
:test_id: image:{badge}Test%20{lvl1}.{lvl2}-{num_test}-pink.svg[link=""]
// Ne pas toucher ⬆️

[width="300%"]
|====
>| Cas de test 4+| {test_id}
>| Titre 4+| {nom_test}
>| Objectif 4+| {objectif}
5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat

^|{lvl1}.{lvl2}.*{num_test}.1* ^|Connecter le port série au site web et ouvrir la console JS. ^|Les données apparaissent sous la forme d'un tableau complet et conforme. ^|Être sur la page index, utiliser Google Chrome. ^|{test_wt}
5+|

5+|Commentaire : Aucun commentaire.
|====


// ///////////////////////////////////////////








////

COMMENTAIRE

=== Fonctionnalités Panel Administrateur
:lvl1: 1
> Ces tests ne regardent que le panel des administrateurs.

==== Gestion des joueurs
:lvl2: 2


// ///////// DEBUT DE NOUVEAU TEST ///////////
// Définissez les informations de votre test!
:num_test: 1
:nom_test: Création d'un nouveau client
:objectif: Vérifier qu'il est possible de créer un nouveau client

// Ne pas toucher ⬇️
:test_id: image:{badge}Test%20{lvl1}.{lvl2}-{num_test}-pink.svg[link=""]
// Ne pas toucher ⬆️

[width="300%"]
|====
>| Cas de test 4+| {test_id}
>| Titre 4+| {nom_test}
>| Objectif 4+| {objectif}
5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|{lvl1}.{lvl2}.*{num_test}.1* ^|Cliquer sur le bouton "Nouveau client". ^|La fenêtre de création des clients s'ouvre. ^| Aucune ^|{test_ko}
5+|

5+|Commentaire : Aucun commentaire.
|====
// ///////////////////////////////////////////


////
